# Generated by Django 4.1.7 on 2023-04-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=40)),
                ('image', models.ImageField(default='null.jpg', upload_to='sample')),
            ],
        ),
    ]
