# Generated by Django 4.1.7 on 2023-04-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='dress', max_length=15),
            preserve_default=False,
        ),
    ]
